---
# tasks file for mediaWiki---
#  tasks:
    - name: Download the media wiki packages
      get_url: 
        url: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.0.tar.gz
        dest: /home/udaytk/mediawiki-1.34.0.tar.gz
        mode: '740'

    - name: Extracting the tar file
      unarchive:
        src: /home/udaytk/mediawiki-1.34.0.tar.gz
        dest: /opt/rh/httpd24/root/var/www/
        remote_src: yes
      become: yes
 
    - name: Creating a soft link
      file:
        src: /opt/rh/httpd24/root/var/www/mediawiki-1.34.0/
        dest: /opt/rh/httpd24/root/var/www/mediawiki
        state: link
      become: yes
     
