---
- name: Install OS packages
  hosts: ansible-target1
  roles:
    - Centos7sclo
    - MariaDB
    - mediaWiki
    - httpd24
    - security 

- name: Setup on 2nd host for db
  hosts: ansible-target2
  roles:
    - Centos7sclo
    - MariaDB

