---
# tasks file for Centos7sclo---
#  tasks:
    - name: Install Software collections for centos 7
      yum:
        name: centos-release-scl
        state: present
      become: true
    - name: Install packages for centos 7 with SCLO
      yum:
        name: 
          - httpd24-httpd
          - php55
          - php55-php
          - php55-php-mbstring
          - php55-php-mysqlnd
          - php55-php-gd
          - php55-php-xml
          - mariadb-server 
          - mariadb
          - MySQL-python
        state: present
      become: true
   
