---
# tasks file for security---
#  tasks:
    #- name: Firewall changes
    #  command: firewall-cmd --permanent --zone=public --add-service=http
    #  become: yes
    
    - name: Firewalld allow for services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        zone: public
        state: enabled
      become: true
      with_items: "{{ firewall_ports }}"
 

    - name: Firewalld service restart
      service:
        name: firewalld
        state: restarted
        enabled: yes
      become: true

    - name: Check if SELinux is enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: SElinux restorecon for Mediawiki directory
      command: restorecon -FR /opt/rh/httpd24/root/var/www/mediawiki-1.34.0/
      become: yes

    - name: SElinux restorecon for Mediawiki file
      command: restorecon -FR /opt/rh/httpd24/root/var/www/mediawiki
      become: yes

